import { Product } from './types'

export const CATEGORIES = ['Всички', 'Дом & Кухня', 'Баня', 'Домашни любимци', 'Инструменти', 'Красота', 'Осветление', 'Автомобили']

export const products: Product[] = [
  {
    id: 'prod-01',
    name: 'Микрофибърни кърпи Ecolino (5 бр.)',
    description: 'Ефективно почистване само с вода, без препарати. Премахва прах, мазнини и замърсявания, без да оставя следи, мъх или петна. Подходяща за стъкла, огледала, душ кабини, инокс, екрани и мебели. XXL размер 30×40 см.',
    price: 13.99,
    images: ['/images/products/prod-01/1.png','/images/products/prod-01/2.jpg','/images/products/prod-01/3.jpg','/images/products/prod-01/4.jpg','/images/products/prod-01/5.jpg','/images/products/prod-01/6.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'компл.', badge: 'Бестселър',
  },
  {
    id: 'prod-02',
    name: 'Таблетки за пералня Calgon 4 в 1',
    description: 'Немско качество — защита от варовик, замърсявания, остатъци и неприятни миризми за пералната машина. Формула 4 в 1, особено подходяща за твърда вода. 1 таблетка на всяко пране.',
    price: 14.90,
    variants: [{ label: '16 броя', price: 14.90 }, { label: '47 броя', price: 24.90 }],
    images: ['/images/products/prod-02/1.jpg','/images/products/prod-02/2.jpg','/images/products/prod-02/3.jpg','/images/products/prod-02/4.jpg','/images/products/prod-02/5.jpg','/images/products/prod-02/6.jpg','/images/products/prod-02/7.jpg','/images/products/prod-02/8.jpg','/images/products/prod-02/9.jpg','/images/products/prod-02/10.jpg','/images/products/prod-02/11.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-03',
    name: 'Хигиенен душ за баня GRIPFLOW',
    description: 'Иновативно решение за по-лесно и по-хигиенично почистване на тоалетна. Осигурява по-добър контрол и достъп до трудни зони, като намалява директния контакт с мрасотия. Лесен монтаж, подходящ за всякакви бани.',
    price: 24.99,
    images: ['/images/products/prod-03/1.png','/images/products/prod-03/2.jpg','/images/products/prod-03/3.jpg','/images/products/prod-03/4.jpg','/images/products/prod-03/5.jpg','/images/products/prod-03/6.jpg','/images/products/prod-03/7.jpg','/images/products/prod-03/8.jpg'],
    category: 'Баня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-04',
    name: 'Самозалепващо фолио за мебели (5 м)',
    description: 'Бързо решение за обновяване и защита на кухненски и мебелни повърхности без ремонт. Лесен монтаж без инструменти, прецизно рязане по линии. Защита от мазнини, влага и замърсявания. Дизайн ял мрамор. 5 м × 40 см.',
    price: 13.90,
    images: ['/images/products/prod-04/1.png','/images/products/prod-04/2.jpg','/images/products/prod-04/3.jpg','/images/products/prod-04/4.jpg','/images/products/prod-04/5.jpg','/images/products/prod-04/6.jpg','/images/products/prod-04/7.jpg','/images/products/prod-04/8.jpg','/images/products/prod-04/9.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-05',
    name: 'Алуминиево фолио за кухня (5 м)',
    description: 'Самозалепващо алуминиево фолио за кухня и мебели. Защита от мазнини, влога и топлина. Лесен монтаж без инструменти, не задържа мрасотия, лесно почистване. Подходящо за шкафове, плотове и стени. 5 м × 40 см.',
    price: 9.90,
    images: ['/images/products/prod-05/1.png','/images/products/prod-05/2.jpg','/images/products/prod-05/3.jpg','/images/products/prod-05/4.jpg','/images/products/prod-05/5.jpg','/images/products/prod-05/6.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-06',
    name: 'Четка за косми GROOMSY',
    description: 'Разресва и събира падащата козина още по времe на сресване. Нежно разресване без дърпане, подходяща за кучета и котки с всякаква козина. Функция за лесно почистване с бутон. Презарежда се (Type C).',
    price: 9.90,
    images: ['/images/products/prod-06/1.png','/images/products/prod-06/2.jpg','/images/products/prod-06/3.jpg','/images/products/prod-06/4.jpg','/images/products/prod-06/5.jpg','/images/products/prod-06/6.jpg','/images/products/prod-06/7.jpg','/images/products/prod-06/8.jpg','/images/products/prod-06/9.jpg','/images/products/prod-06/10.jpg','/images/products/prod-06/11.jpg'],
    category: 'Домашни любимци', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-07',
    name: 'Паста за ремонт на стени WallRepair (250 г)',
    description: 'Бързо решение за поправка на малки дефекти по стените без нужда от майстор. Запълва пукнатини, дупки и драскотини. Бързосъхнеща формула, гладък завършек, не се рони и не се лющи. Подходящо за кухня и баня.',
    price: 14.90,
    images: ['/images/products/prod-07/new-thumb.png','/images/products/prod-07/1.jpg','/images/products/prod-07/2.png','/images/products/prod-07/3.jpg','/images/products/prod-07/4.jpg','/images/products/prod-07/5.jpg','/images/products/prod-07/6.jpg','/images/products/prod-07/7.jpg','/images/products/prod-07/8.png','/images/products/prod-07/9.png'],
    category: 'Инструменти', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-09',
    name: 'Антивибрационни крачета SLIPSTOP (4 бр.)',
    description: 'Намаляват вибрациите до 94.7% и премахват досадния шум при работа на перални и сушилни. Предпазват пода от надраскване. Лесен монтаж, универсален размер. Материал: гума + PVC.',
    price: 6.90,
    images: ['/images/products/prod-09/1.png','/images/products/prod-09/2.jpg','/images/products/prod-09/3.jpg','/images/products/prod-09/4.jpg','/images/products/prod-09/5.jpg','/images/products/prod-09/6.jpg','/images/products/prod-09/7.jpg','/images/products/prod-09/8.jpg','/images/products/prod-09/9.jpg','/images/products/prod-09/10.jpg','/images/products/prod-09/11.jpg','/images/products/prod-09/12.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-10',
    name: 'Масажен душ с филтри SHOWERELAX',
    description: 'Няколко режима на водна струя за по-комфортно и релаксиращо изживяване при къпане. Масажиращ и дъждовен ефект. Включени 5 филтра за по-чиста вода. Лесен монтаж за минути, подходящ за всяка стандартна баня.',
    price: 14.90,
    images: ['/images/products/prod-10/1.png','/images/products/prod-10/2.png','/images/products/prod-10/3.jpg','/images/products/prod-10/4.jpg','/images/products/prod-10/5.jpg','/images/products/prod-10/6.png'],
    category: 'Баня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-11',
    name: 'Спрей четка 2 в 1 за прозорци',
    description: 'Почиства и подсушава с един инструмент, без да оставя водни следи. Вграден спрей резервоар, ергономична дръжка против приплъзване. За прозорци, огледала, душ кабини и автомобилни стъкла.',
    price: 14.90,
    images: ['/images/products/prod-11/1.png','/images/products/prod-11/2.jpg','/images/products/prod-11/3.jpg','/images/products/prod-11/4.jpg','/images/products/prod-11/5.jpg','/images/products/prod-11/6.jpg','/images/products/prod-11/7.jpg','/images/products/prod-11/8.jpg','/images/products/prod-11/9.jpg','/images/products/prod-11/10.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-12',
    name: 'Комплект за почистване на хладилник (5 части)',
    description: 'Премахва натрупана мрасотия и бактерии от дренажната система на хладилника. Предотвратява запушвания и течове, намалява неприятните миризми. Гъвкава конструкция за труднодостъпни места, без специални инструменти.',
    price: 9.99,
    images: ['/images/products/prod-12/new-thumb.jpg','/images/products/prod-12/1.png','/images/products/prod-12/2.jpg','/images/products/prod-12/3.jpg','/images/products/prod-12/4.jpg','/images/products/prod-12/5.jpg','/images/products/prod-12/6.jpg','/images/products/prod-12/7.jpg','/images/products/prod-12/8.jpg','/images/products/prod-12/9.jpg','/images/products/prod-12/10.jpg','/images/products/prod-12/11.jpeg','/images/products/prod-12/12.jpg','/images/products/prod-12/13.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-13',
    name: 'Торбичка за пране на обувки',
    description: 'Дълбоко почистване с микрофибър (шенил), 360° измиване без риск от деформация. Скрит цип за допълнителна защита. Подходяща за спортни и текстилни обувки. Размер: 39.1×19.9 см.',
    price: 9.90,
    images: ['/images/products/prod-13/new-thumb.png','/images/products/prod-13/1.png','/images/products/prod-13/2.jpg','/images/products/prod-13/3.jpg','/images/products/prod-13/4.jpg','/images/products/prod-13/5.jpg','/images/products/prod-13/6.jpg','/images/products/prod-13/7.jpg','/images/products/prod-13/8.jpg','/images/products/prod-13/9.jpg','/images/products/prod-13/10.jpg','/images/products/prod-13/11.jpg','/images/products/prod-13/12.jpg','/images/products/prod-13/13.jpg','/images/products/prod-13/14.jpg','/images/products/prod-13/15.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-14',
    name: 'Комплект за преместване на мебели с лост',
    description: 'Лесно преместване на тежки мебели до 150 кг без усилие и без надраскване на пода. Повдигащ лост + 4 подложки с колела. Без нужда от инструменти. За перални, хладилници, шкафове и пещки.',
    price: 14.90,
    images: ['/images/products/prod-14/1.png','/images/products/prod-14/2.jpg','/images/products/prod-14/3.jpg','/images/products/prod-14/4.jpg','/images/products/prod-14/5.jpg','/images/products/prod-14/6.jpg','/images/products/prod-14/7.jpg','/images/products/prod-14/8.jpg','/images/products/prod-14/9.jpg','/images/products/prod-14/10.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-16',
    name: 'LED лампа за четене на книга',
    description: 'Локално осветление директно върху страницата без да се нарушава комфорта на околните. Щадяща светлина за очите, регулируема яркост. Акумулаторна батерия до 35 часа работа. Лек и преносим дизайн.',
    price: 19.99,
    images: ['/images/products/prod-16/1.png','/images/products/prod-16/2.jpg','/images/products/prod-16/3.jpg','/images/products/prod-16/4.jpg','/images/products/prod-16/5.png'],
    category: 'Осветление', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-17',
    name: 'Водоустойчиво хидроизолиращо лепило (300 г)',
    description: 'Запечатва течове, пукнатини и проблемни зони. Устойчиво на дъжд, слънце, студ и влога. Силна адхезия към бетон, метал, дърво и плочки. Лесно нанасяне без специални инструменти. Налично и в 500 г (19.90 €).',
    price: 14.90,
    images: ['/images/products/prod-17/1.png','/images/products/prod-17/2.jpg','/images/products/prod-17/3.jpg','/images/products/prod-17/4.jpg','/images/products/prod-17/5.jpg','/images/products/prod-17/6.jpg','/images/products/prod-17/7.jpg'],
    category: 'Инструменти', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-18',
    name: 'Магнитна запечатваща машинка',
    description: 'Запечатва пакети за секунди и поддържа храната свежа по-дълго. Магнитно закрепване към хладилник, вградено острие за отваряне. Дигитален дисплей, 6 температурни нива. Презарежда се (Type C).',
    price: 19.90,
    images: ['/images/products/prod-18/1.png','/images/products/prod-18/2.jpg','/images/products/prod-18/3.jpg','/images/products/prod-18/4.jpg','/images/products/prod-18/5.jpg','/images/products/prod-18/6.jpg','/images/products/prod-18/7.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-19',
    name: 'Преса за коса с вълнообразен ефект',
    description: 'Бързо оформяне на обемни и естествени вълни у дома. Керамично покритие, 4 температурни настройки (160–220°C). Двоен цилиндър за по-бързо оформяне. Защита от прегряване. Цвят лилав, EU 220-240V.',
    price: 24.90,
    images: ['/images/products/prod-19/1.png','/images/products/prod-19/2.png','/images/products/prod-19/3.png','/images/products/prod-19/4.jpg','/images/products/prod-19/5.jpg'],
    category: 'Красота', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-20',
    name: 'Телескопична стойка с колела за мебели',
    description: 'Лесно преместване на тежки мебели и електроуреди до 200 кг без усилие. 12 здрави колела, вградени спирачки за стабилност, телескопичен дизайн. Защитава подовите настилки. За перални, хладилници и шкафове.',
    price: 19.90,
    images: ['/images/products/prod-20/1.png','/images/products/prod-20/2.png','/images/products/prod-20/3.png','/images/products/prod-20/4.png','/images/products/prod-20/5.png','/images/products/prod-20/6.png','/images/products/prod-20/7.jpg','/images/products/prod-20/8.jpg','/images/products/prod-20/9.png'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-21',
    name: 'Ролер за косми FURLOST',
    description: 'Ефективно премахва косми от котки и кучета с едно движение. Без лепящи ленти и консумативи — многократна употреба. Компактен, лесен за пренасяне. За мебели, дрехи, килими и автомобилни седалки. 44×18 см.',
    price: 9.99,
    images: ['/images/products/prod-21/1.png','/images/products/prod-21/2.jpg','/images/products/prod-21/3.jpg','/images/products/prod-21/4.jpg','/images/products/prod-21/5.jpg','/images/products/prod-21/6.jpg','/images/products/prod-21/7.jpg','/images/products/prod-21/8.jpg','/images/products/prod-21/9.jpg'],
    category: 'Домашни любимци', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-22',
    name: 'Безжична мини прахосмукачка VClean 2 в 1',
    description: 'Мощност 9000Pa. Функции: прахосмукачка, издухване и почистване на труднодостъпни места. Акумулаторна батерия 2000mAh, USB зареждане. Комплект 12 части. Тегло 600 г. За дома, автомобила и офиса.',
    price: 19.99,
    images: ['/images/products/prod-22/1.png','/images/products/prod-22/2.png','/images/products/prod-22/3.png','/images/products/prod-22/4.png','/images/products/prod-22/5.png','/images/products/prod-22/6.png','/images/products/prod-22/7.png','/images/products/prod-22/8.png','/images/products/prod-22/9.png','/images/products/prod-22/10.png','/images/products/prod-22/11.png'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-23b',
    name: 'Преносима бутилка за вода от неръждаема стомана за домашни любимци',
    description: 'Практично решение за осигуряване на вода за кучета по време на разходки, пътувания и активности на открито. Сферична форма с вградена купичка за пиене. Изработена от неръждаема стомана 304. Система против разливане, вградена кука за закачане. Подходяща за разходки, планина, пътувания и къмпинг.',
    price: 19.90,
    images: ['/images/products/prod-23b/0.png','/images/products/prod-23b/1.jpg','/images/products/prod-23b/2.jpg','/images/products/prod-23b/3.jpg','/images/products/prod-23b/4.jpg','/images/products/prod-23b/5.jpg','/images/products/prod-23b/6.jpg','/images/products/prod-23b/7.jpg','/images/products/prod-23b/8.jpg','/images/products/prod-23b/9.jpg'],
    category: 'Домашни любимци', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-24',
    name: 'Автоматичен сгъваем простор за дрехи (5.1 м)',
    description: 'Метално въже с дължина 5.1 м. Автоматичен прибиращ механизъм — разпъва се при нужда и се прибира след употреба. Здрав и устойчив корпус, лесен монтаж на стена. За апартаменти, бани и тераси.',
    price: 24.90,
    images: ['/images/products/prod-24/1.png','/images/products/prod-24/2.png','/images/products/prod-24/3.jpg','/images/products/prod-24/4.png','/images/products/prod-24/5.jpg','/images/products/prod-24/6.jpg','/images/products/prod-24/7.jpg','/images/products/prod-24/8.jpg','/images/products/prod-24/9.jpg','/images/products/prod-24/10.jpg','/images/products/prod-24/11.jpg','/images/products/prod-24/12.jpg','/images/products/prod-24/13.jpg','/images/products/prod-24/14.png'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-25',
    name: 'Регулируем рафт с закачалка за баня',
    description: 'Комбинира закачалка за кърпи и подвижен рафт за аксесоари. Здрав стоманен корпус, лесен монтаж с включени крепежи. Спестява място в банята. Размер: 57.4×20.5×16.5 см. Цвят: черен.',
    price: 19.99,
    images: ['/images/products/prod-25/1.png','/images/products/prod-25/2.jpg','/images/products/prod-25/3.jpg','/images/products/prod-25/4.jpg','/images/products/prod-25/5.jpg','/images/products/prod-25/6.jpg','/images/products/prod-25/7.jpg','/images/products/prod-25/8.jpg','/images/products/prod-25/9.jpg','/images/products/prod-25/10.jpg'],
    category: 'Баня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-26',
    name: 'Помощна дръжка с вакуумни вендузи',
    description: 'Допълнителна стабилност и безопасност в банята без пробиване или монтаж. Закрепва с вакуумни вендузи за секунди. Лесно преместване и повторна употреба. За плочки, стъкло и твърда пластмаса.',
    price: 12.90,
    images: ['/images/products/prod-26/1.png','/images/products/prod-26/2.jpg','/images/products/prod-26/3.jpg','/images/products/prod-26/4.jpg','/images/products/prod-26/5.jpg','/images/products/prod-26/6.jpg','/images/products/prod-26/7.jpg','/images/products/prod-26/8.jpg','/images/products/prod-26/9.jpg','/images/products/prod-26/10.jpg','/images/products/prod-26/11.jpg'],
    category: 'Баня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-27',
    name: 'Безжични LED светлини за автомобил / дрон (4 бр.)',
    description: '8 цвята светлина, 10 режима на работа. Дистанционно управление до 7 м, USB презареждане, водоустойчивост IP65. Функция памет на последния режим. За автомобили, мотори, велосипеди и дронове.',
    price: 19.90,
    images: ['/images/products/prod-27/new-thumb.jpg','/images/products/prod-27/1.png','/images/products/prod-27/2.jpg','/images/products/prod-27/3.jpg','/images/products/prod-27/4.jpg','/images/products/prod-27/5.jpg','/images/products/prod-27/6.jpg','/images/products/prod-27/7.jpg','/images/products/prod-27/8.jpg','/images/products/prod-27/9.jpg','/images/products/prod-27/10.jpg','/images/products/prod-27/11.jpg','/images/products/prod-27/12.jpg','/images/products/prod-27/13.jpg'],
    category: 'Автомобили', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-28',
    name: 'Соларна LED лампа за къмпинг',
    description: 'Слънчево и USB-C зареждане, до 10 часа работа. 3 режима на светлина (силен, среден, слаб). Вградена кука за окачване, лека и компактна. За къмпинг, риболов, туризъм, градина и аварийни ситуации.',
    price: 4.90,
    images: ['/images/products/prod-28/1.png','/images/products/prod-28/2.jpg','/images/products/prod-28/3.jpg','/images/products/prod-28/4.jpg','/images/products/prod-28/5.jpg','/images/products/prod-28/6.jpg','/images/products/prod-28/7.jpg','/images/products/prod-28/8.jpg','/images/products/prod-28/9.jpg','/images/products/prod-28/10.jpg'],
    category: 'Осветление', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-30',
    name: 'Удължител за кухненски кран (аератор)',
    description: '360° въртящ се накрайник против пръски. Икономия на вода без загуба на налягане. Бърз монтаж без инструменти. Подходящ за кухня и баня. Лесно поставяне и сваляне. Цвят: сребрист / черен.',
    price: 14.90,
    images: ['/images/products/prod-30/1.png','/images/products/prod-30/2.jpg','/images/products/prod-30/3.jpg','/images/products/prod-30/4.jpg','/images/products/prod-30/5.jpg','/images/products/prod-30/6.jpg','/images/products/prod-30/7.jpg','/images/products/prod-30/8.jpg','/images/products/prod-30/9.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-31',
    name: 'Дигитален нивелир с LCD дисплей',
    description: 'Точност до 0.01°, измерване на 360°. Магнитна основа за стабилно закрепване. Моментални измервания в реално времe. Устойчив на удари и влога. За монтаж на мебели, гипсокартон, строителни конструкции.',
    price: 24.90,
    images: ['/images/products/prod-31/new-thumb.png','/images/products/prod-31/1.png','/images/products/prod-31/2.jpg','/images/products/prod-31/3.jpg','/images/products/prod-31/4.jpg','/images/products/prod-31/5.jpg','/images/products/prod-31/6.jpg','/images/products/prod-31/7.jpg','/images/products/prod-31/8.jpg','/images/products/prod-31/9.jpg','/images/products/prod-31/10.jpg'],
    category: 'Инструменти', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-32',
    name: 'Спрей четка за коса 2 в 1',
    description: 'Разресва и овлажнява едновременно. Вграден пулверизатор за фина мъгла, намалява скъбването и накъсването. Ергономична дръжка, вграден резервоар за вода или балсам. По-гладка и освежена коса за секунди.',
    price: 14.90,
    images: ['/images/products/prod-32/1.png','/images/products/prod-32/2.jpg','/images/products/prod-32/3.jpg','/images/products/prod-32/4.jpg','/images/products/prod-32/5.jpg','/images/products/prod-32/6.jpg','/images/products/prod-32/7.jpg','/images/products/prod-32/8.jpg','/images/products/prod-32/9.jpg','/images/products/prod-32/10.jpg','/images/products/prod-32/11.jpg','/images/products/prod-32/12.jpg','/images/products/prod-32/13.png'],
    category: 'Красота', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-33',
    name: 'Четки за винтоверт (3 бр.)',
    description: 'Захващат упорита мрасотия за минути. Съвместими с винтоверт и бормашина. 3 различни размера, достигат труднодостъпни места. Не драскат повърхностите при правилна употреба. За бани, джанти, фуги и мебели.',
    price: 9.90,
    images: ['/images/products/prod-33/1.png','/images/products/prod-33/2.png','/images/products/prod-33/3.png','/images/products/prod-33/4.png','/images/products/prod-33/5.jpg','/images/products/prod-33/6.jpg','/images/products/prod-33/7.jpg','/images/products/prod-33/8.jpg','/images/products/prod-33/9.png','/images/products/prod-33/10.png','/images/products/prod-33/11.jpg'],
    category: 'Инструменти', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-35',
    name: 'Машинка за стреч фолио с резец – HouseholdCutter',
    description: 'Практичен помощник за бързо и прецизно рязане на стреч фолио, алуминиево фолио и хартия за печене. Вграден плъзгащ резец, компактен дизайн, безопасно скрито острие. Лесна употреба с едно движение. Размер 37×6.5 см, подходяща за ролки до 30 см ширина.',
    price: 14.90,
    images: ['/images/products/prod-35/new-thumb.png','/images/products/prod-35/1.jpg','/images/products/prod-35/2.png','/images/products/prod-35/3.jpg','/images/products/prod-35/4.jpg','/images/products/prod-35/5.jpg','/images/products/prod-35/6.jpg','/images/products/prod-35/7.jpg','/images/products/prod-35/8.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-36',
    name: 'Преносим мини вентилатор SULVGO с LCD дисплей',
    description: 'Компактен вентилатор с въртене на 360° и 3 степени на охлаждане. LCD дисплей за лесен контрол, вградена LED светлина, тих режим. Презарежда се с Type-C за около 66 минути, работи ~5 часа. За работа, спорт, пътуване и ежедневна употреба.',
    price: 19.90,
    images: ['/images/products/prod-36/new-thumb.jpg','/images/products/prod-36/1.jpg','/images/products/prod-36/2.jpg','/images/products/prod-36/3.jpg','/images/products/prod-36/4.jpg','/images/products/prod-36/5.jpg','/images/products/prod-36/6.jpg','/images/products/prod-36/7.jpg','/images/products/prod-36/8.jpg','/images/products/prod-36/9.jpg','/images/products/prod-36/10.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-37',
    name: 'Смарт-адаптер с автоматично изключване Type-C',
    description: 'Интелигентен адаптер, който автоматично прекъсва зареждането при 100% батерия. Предпазва от презареждане и излишно натоварване на устройството. Поддържа бързо зареждане. Съвместим със смартфони, таблети, слушалки и всички устройства с Type-C порт.',
    price: 14.90,
    images: ['/images/products/prod-37/new-thumb.png','/images/products/prod-37/0.jpg','/images/products/prod-37/1.jpg','/images/products/prod-37/2.jpg','/images/products/prod-37/3.jpg','/images/products/prod-37/4.jpg','/images/products/prod-37/5.jpg','/images/products/prod-37/6.jpg','/images/products/prod-37/7.png','/images/products/prod-37/8.jpeg','/images/products/prod-37/9.jpg','/images/products/prod-37/10.jpg','/images/products/prod-37/11.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-38',
    name: 'Самозалепваща RGB LED лента (5 м) с дистанционно',
    description: 'Добави цветна атмосфера към всяко помещение. 5 м самозалепваща лента, дистанционно управление с 24 бутона, 6 режима на осветяване. Ниска консумация, живот над 50 000 часа. Комплектът включва лента, контролер, дистанционно и адаптер 12V. За дома, офиса и гейминг пространства.',
    price: 12.90,
    images: ['/images/products/prod-38/1.jpeg','/images/products/prod-38/2.jpeg','/images/products/prod-38/3.jpeg','/images/products/prod-38/4.jpeg','/images/products/prod-38/5.jpeg','/images/products/prod-38/6.jpeg','/images/products/prod-38/7.jpg','/images/products/prod-38/8.jpeg','/images/products/prod-38/9.jpeg','/images/products/prod-38/10.jpeg'],
    category: 'Осветление', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-39',
    name: 'Професионално кухненско ренде 9 в 1',
    description: 'Многофункционален кухненски помощник с 9 функции в един уред. Рязане на филийки, жулиени, кубчета и сламки, регулируема дебелина. Вграден контейнер за събиране на продуктите, компактен и сгъваем дизайн. Спестява време и бъркотия в кухнята.',
    price: 34.90,
    images: ['/images/products/prod-39/1.png','/images/products/prod-39/2.png','/images/products/prod-39/2.jpg','/images/products/prod-39/3.jpg','/images/products/prod-39/4.jpg','/images/products/prod-39/5.jpg','/images/products/prod-39/6.jpg','/images/products/prod-39/7.jpg','/images/products/prod-39/8.jpg','/images/products/prod-39/9.jpg','/images/products/prod-39/10.jpg','/images/products/prod-39/15.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-40',
    name: 'PVC стикер за дискретност на прозорци (60×200 см)',
    description: 'Практично матирано фолио за повече поверителност без да затъмнява помещението. Самозалепващ монтаж, UV защита, модерен декоративен ефект. Лесно почистване. За прозорци, стъклени врати, витрини, бани и офиси. Размер 60×200 см, материал PVC.',
    price: 14.90,
    images: ['/images/products/prod-40/1.jpg','/images/products/prod-40/2.jpg','/images/products/prod-40/3.jpg','/images/products/prod-40/4.jpg','/images/products/prod-40/5.jpg','/images/products/prod-40/6.jpg','/images/products/prod-40/7.jpg','/images/products/prod-40/8.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-41',
    name: 'Хидроизолиращо покритие AquaCoatz™ (1 кг)',
    description: 'Еластично водоустойчиво покритие против течове и влага. Устойчиво на UV лъчи и температури от -40°C до +80°C. Силно сцепление към метал, бетон и асфалт. Лесно нанасяне с четка, валяк или пръскачка.',
    price: 24.90,
    images: ['/images/products/prod-41/1.jpg','/images/products/prod-41/2.jpg','/images/products/prod-41/3.jpg','/images/products/prod-41/4.jpg','/images/products/prod-41/5.jpg','/images/products/prod-41/6.jpg'],
    category: 'Инструменти', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-42',
    name: 'Препарат за почистване на хладилници DR.BECKMANN (250 мл)',
    description: 'Хигиенично почистване на хладилници, микровълнови и килери с биоалкохол. Абсорбира неприятни миризми и премахва лека слана. Действа при ниски температури, без мирис. Немско качество.',
    price: 9.90,
    images: ['/images/products/prod-42/1.jpg','/images/products/prod-42/2.jpg','/images/products/prod-42/3.jpg','/images/products/prod-42/4.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-43',
    name: 'Самозалепващи акрилни огледални стикери (4 бр., 30×30 см)',
    description: 'Декоративни огледални плочки с висока отражателна способност. Самозалепващ монтаж без пробиване и инструменти. По-леки и устойчиви на счупване от стъклени огледала. За стени, врати, шкафове и DIY проекти.',
    price: 14.90,
    images: ['/images/products/prod-43/1.jpg','/images/products/prod-43/2.jpg','/images/products/prod-43/3.jpg','/images/products/prod-43/4.jpg','/images/products/prod-43/5.jpg','/images/products/prod-43/6.jpg','/images/products/prod-43/7.jpg','/images/products/prod-43/8.jpg','/images/products/prod-43/9.jpg','/images/products/prod-43/10.jpg','/images/products/prod-43/11.jpg','/images/products/prod-43/12.jpg','/images/products/prod-43/13.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-44',
    name: 'LED лампа за шкаф със сензор за движение (30 см)',
    description: 'Безжично акумулаторно осветление с автоматично включване при движение до 3 м. Регулируема цветова температура 3000K–6500K, 3 режима (ON/OFF/AUTO). USB Type-C зареждане. За кухня, гардероб, антре и гараж.',
    price: 14.90,
    images: ['/images/products/prod-44/1.jpg','/images/products/prod-44/2.jpg','/images/products/prod-44/3.jpg','/images/products/prod-44/4.jpg','/images/products/prod-44/5.jpg','/images/products/prod-44/6.jpg','/images/products/prod-44/7.jpg','/images/products/prod-44/8.jpg','/images/products/prod-44/9.jpg','/images/products/prod-44/10.jpg','/images/products/prod-44/11.jpg','/images/products/prod-44/12.jpg','/images/products/prod-44/13.jpg','/images/products/prod-44/14.jpg','/images/products/prod-44/15.jpg','/images/products/prod-44/16.jpg','/images/products/prod-44/17.jpg','/images/products/prod-44/18.jpg','/images/products/prod-44/19.jpg'],
    category: 'Осветление', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-45',
    name: 'Електрическа въртяща се четка за почистване ROTOBRUSH (9 приставки)',
    description: 'Мощно почистване на плочки, фуги, мивки и джанти само с вода. До 300 оборота в минута, телескопична дръжка до 105 см. Акумулаторно захранване, водоустойчив превключвател. 9 приставки за различни повърхности.',
    price: 19.90,
    images: ['/images/products/prod-45/1.jpg','/images/products/prod-45/2.jpg','/images/products/prod-45/3.jpg','/images/products/prod-45/4.jpg','/images/products/prod-45/5.jpg','/images/products/prod-45/6.jpg','/images/products/prod-45/7.jpg','/images/products/prod-45/8.jpg','/images/products/prod-45/9.jpg','/images/products/prod-45/10.jpg','/images/products/prod-45/11.jpg','/images/products/prod-45/12.jpg','/images/products/prod-45/13.jpg','/images/products/prod-45/14.png'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-46',
    name: 'Книга-сейф с ключ',
    description: 'Дискретно метално отделение за пари, бижута и документи, скрито в реалистична книга. Заключване с ключ, компактен размер за библиотека или рафт. Комбинация от метал и картон за здравина.',
    price: 14.90,
    images: ['/images/products/prod-46/1.jpg','/images/products/prod-46/2.jpg','/images/products/prod-46/3.jpg','/images/products/prod-46/4.jpg','/images/products/prod-46/5.jpg','/images/products/prod-46/6.jpg','/images/products/prod-46/7.jpg','/images/products/prod-46/8.jpg','/images/products/prod-46/9.jpg','/images/products/prod-46/10.jpg','/images/products/prod-46/11.jpg','/images/products/prod-46/12.jpg','/images/products/prod-46/13.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-47',
    name: 'Сушилник за съдове от неръждаема стомана (двуетажен)',
    description: 'Модулна организация за чинии, чаши и прибори върху кухненския плот. Неръждаема стомана, устойчива на ръжда и лющене. Стабилна основа, лесно сглобяване без инструменти. Модерен черен дизайн.',
    price: 19.90,
    images: ['/images/products/prod-47/1.jpg','/images/products/prod-47/2.jpg','/images/products/prod-47/3.jpg','/images/products/prod-47/4.jpg','/images/products/prod-47/5.jpg','/images/products/prod-47/6.jpg','/images/products/prod-47/7.jpg','/images/products/prod-47/8.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-48',
    name: 'Уплътнителни подложки за процеп на автомобилни седалки (2 бр.)',
    description: 'Запълва пролуката между седалката и централната конзола, за да не изпадат телефон, ключове и монети. Ограничава натрупването на трохи и прах. Полиуретан, за водача и пътника. 45×8×7,5 см.',
    price: 9.90,
    images: ['/images/products/prod-48/1.jpg','/images/products/prod-48/2.jpg','/images/products/prod-48/3.jpg','/images/products/prod-48/4.jpg','/images/products/prod-48/5.jpg','/images/products/prod-48/6.jpg','/images/products/prod-48/7.jpg','/images/products/prod-48/8.jpg','/images/products/prod-48/9.png','/images/products/prod-48/10.png','/images/products/prod-48/11.jpg','/images/products/prod-48/12.jpg'],
    category: 'Автомобили', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-49',
    name: 'Двойнозалепващо силиконово гел тиксо (3 м)',
    description: 'Гъвкаво водоустойчиво тиксо за закрепване без пробиване на стени. Измива се с вода и се използва многократно. Реже се на отделни лепенки според нуждите. За картини, огледала, закачалки и аксесоари.',
    price: 6.90,
    images: ['/images/products/prod-49/1.jpg','/images/products/prod-49/2.jpg','/images/products/prod-49/3.jpg','/images/products/prod-49/4.jpg','/images/products/prod-49/5.jpg','/images/products/prod-49/6.jpg','/images/products/prod-49/7.jpg','/images/products/prod-49/8.jpg','/images/products/prod-49/9.png','/images/products/prod-49/10.jpg','/images/products/prod-49/11.jpg','/images/products/prod-49/12.jpg','/images/products/prod-49/13.jpg','/images/products/prod-49/14.jpg','/images/products/prod-49/15.jpg','/images/products/prod-49/16.jpg'],
    category: 'Инструменти', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-50',
    name: 'Подвижен накрайник за чешма от неръждаема стомана (360°)',
    description: 'Гъвкав метален накрайник с 2 режима на струята и въртене на 360°. Филтриращ елемент, ограничава пръските около мивката. Резба M22/M24×1, включва уплътнители за монтаж. За кухня и баня.',
    price: 16.90,
    images: ['/images/products/prod-50/1.jpg','/images/products/prod-50/2.jpg','/images/products/prod-50/3.jpg','/images/products/prod-50/4.png','/images/products/prod-50/5.jpg','/images/products/prod-50/6.jpg','/images/products/prod-50/7.jpg','/images/products/prod-50/8.jpg','/images/products/prod-50/9.jpg','/images/products/prod-50/10.jpg','/images/products/prod-50/11.jpg','/images/products/prod-50/12.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-51',
    name: 'Ръчна преса за пържени картофки',
    description: 'Нарязва картофи, моркови и ябълки на равномерни парчета с едно натискане. Компактна конструкция от пластмаса и неръждаема стомана. Спестява време при подготовка на храна. Лесна за съхранение.',
    price: 9.90,
    images: ['/images/products/prod-51/1.jpg','/images/products/prod-51/2.jpg','/images/products/prod-51/3.jpg','/images/products/prod-51/4.png','/images/products/prod-51/5.jpg','/images/products/prod-51/6.jpg','/images/products/prod-51/7.jpg','/images/products/prod-51/8.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-52',
    name: 'Сгъваема дъска за рязане 3 в 1 (дъска, леген и гевгир)',
    description: 'Съчетава дъска за рязане, леген за измиване и отцеждане в един компактен продукт. Сгъва се до 3 см за лесно съхранение. Anti-slip основа, устойчива на BPA, подходяща за съдомиялна машина.',
    price: 14.90,
    images: ['/images/products/prod-52/1.jpg','/images/products/prod-52/2.jpg','/images/products/prod-52/3.jpg','/images/products/prod-52/4.jpg','/images/products/prod-52/5.jpg','/images/products/prod-52/6.jpg','/images/products/prod-52/7.jpg','/images/products/prod-52/8.jpg','/images/products/prod-52/9.jpg','/images/products/prod-52/10.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-53',
    name: 'Луксозна душ система 4 в 1 с цифров температурен дисплей',
    description: 'Дъждовен душ, ръчен душ, чучур за вана и биде функция в една колона. Цифров дисплей за температурата без нужда от захранване. Месинг, мед и PVC с антикорозионно покритие. Регулируема височина.',
    price: 59.90,
    images: ['/images/products/prod-53/1.jpg','/images/products/prod-53/2.jpg','/images/products/prod-53/3.jpg','/images/products/prod-53/4.jpg','/images/products/prod-53/5.jpg','/images/products/prod-53/6.jpg','/images/products/prod-53/7.jpg','/images/products/prod-53/8.jpg','/images/products/prod-53/9.jpg','/images/products/prod-53/10.jpg','/images/products/prod-53/11.jpg','/images/products/prod-53/12.jpg','/images/products/prod-53/13.jpg','/images/products/prod-53/14.jpg','/images/products/prod-53/15.jpg','/images/products/prod-53/16.jpg'],
    category: 'Баня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-54',
    name: 'Премиум луксозна душ система 4 в 1 с термостат и LED дисплей',
    description: 'Термостатичен контрол на температурата с предварително зададена защита от 38°C и LED дисплей, захранван от водния поток. Голяма душ глава 300×200 мм с въртене на 360°, ръчен душ с 3 режима и биде функция. Месинг и неръждаема стомана.',
    price: 79.90,
    images: ['/images/products/prod-54/1.jpg','/images/products/prod-54/2.jpg','/images/products/prod-54/3.jpg','/images/products/prod-54/4.jpg','/images/products/prod-54/5.jpg','/images/products/prod-54/6.jpg','/images/products/prod-54/7.jpg','/images/products/prod-54/8.jpg','/images/products/prod-54/9.jpg','/images/products/prod-54/10.jpg','/images/products/prod-54/11.jpg','/images/products/prod-54/12.jpg','/images/products/prod-54/13.jpg'],
    category: 'Баня', inStock: true, minOrder: 1, unit: 'бр.',
  },
]

export function getProduct(id: string): Product | undefined {
  return products.find(p => p.id === id)
}

export function getProducts(category?: string): Product[] {
  if (!category || category === 'Всички') return products
  return products.filter(p => p.category === category)
}
