import { Product } from './types'

export const CATEGORIES = ['Всички', 'Дом & Кухня', 'Баня', 'Домашни любимци', 'Инструменти', 'Красота', 'Осветление', 'Автомобили']

export const products: Product[] = [
  {
    id: 'prod-01',
    name: 'Микрофибърни кърпи Ecolino (5 бр.)',
    description: 'Ефективно почистване само с вода, без препарати. Премахва прах, мазнини и замърсявания, без да оставя следи, мъх или петна. Подходяща за стъкла, огледала, душ кабини, инокс, екрани и мебели. XXL размер 30×40 см.',
    price: 13.99,
    images: ['/images/products/prod-01/1.png','/images/products/prod-01/2.jpg','/images/products/prod-01/3.jpg','/images/products/prod-01/4.jpg','/images/products/prod-01/5.jpg','/images/products/prod-01/6.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-02',
    name: 'Таблетки за пералня (12 бр.)',
    description: 'Почиства пералнята от натрупани замърсявания, котлен камък и остатъци от препарати. Неутрализира неприятни миризми и поддържа по-висока ефективност на уреда. 1 таблетка месечно — 12 месеца поддръжка.',
    price: 9.90,
    images: ['/images/products/prod-02/1.png','/images/products/prod-02/2.jpg','/images/products/prod-02/3.jpg','/images/products/prod-02/4.jpg','/images/products/prod-02/5.jpg','/images/products/prod-02/6.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-03',
    name: 'Хигиенен душ за баня GRIPFLOW',
    description: 'Иновативно решение за по-лесно и по-хигиенично почистване на тоалетна. Осигурява по-добър контрол и достъп до трудни зони, като намалява директния контакт с мрасотия. Лесен монтаж, подходящ за всякакви бани.',
    price: 24.99,
    images: ['/images/products/prod-03/1.png','/images/products/prod-03/2.jpg','/images/products/prod-03/3.jpg','/images/products/prod-03/4.jpg','/images/products/prod-03/5.jpg','/images/products/prod-03/6.jpg','/images/products/prod-03/7.jpg','/images/products/prod-03/8.jpg'],
    category: 'Баня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-04',
    name: 'Самозалепващо фолио за мебели (5 м)',
    description: 'Бързо решение за обновяване и защита на кухненски и мебелни повърхности без ремонт. Лесен монтаж без инструменти, прецизно рязане по линии. Защита от мазнини, влага и замърсявания. Дизайн ял мрамор. 5 м × 40 см.',
    price: 13.90,
    images: ['/images/products/prod-04/1.png','/images/products/prod-04/2.jpg','/images/products/prod-04/3.jpg','/images/products/prod-04/4.jpg','/images/products/prod-04/5.jpg','/images/products/prod-04/6.jpg','/images/products/prod-04/7.jpg','/images/products/prod-04/8.jpg','/images/products/prod-04/9.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-05',
    name: 'Алуминиево фолио за кухня (5 м)',
    description: 'Самозалепващо алуминиево фолио за кухня и мебели. Защита от мазнини, влога и топлина. Лесен монтаж без инструменти, не задържа мрасотия, лесно почистване. Подходящо за шкафове, плотове и стени. 5 м × 40 см.',
    price: 9.90,
    images: ['/images/products/prod-05/1.png','/images/products/prod-05/2.jpg','/images/products/prod-05/3.jpg','/images/products/prod-05/4.jpg','/images/products/prod-05/5.jpg','/images/products/prod-05/6.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-06',
    name: 'Четка за косми GROOMSY',
    description: 'Разресва и събира падащата козина още по времe на сресване. Нежно разресване без дърпане, подходяща за кучета и котки с всякаква козина. Функция за лесно почистване с бутон. Презарежда се (Type C).',
    price: 9.90,
    images: ['/images/products/prod-06/1.png','/images/products/prod-06/2.jpg','/images/products/prod-06/3.jpg','/images/products/prod-06/4.jpg','/images/products/prod-06/5.jpg','/images/products/prod-06/6.jpg','/images/products/prod-06/7.jpg','/images/products/prod-06/8.jpg','/images/products/prod-06/9.jpg','/images/products/prod-06/10.jpg','/images/products/prod-06/11.jpg'],
    category: 'Домашни любимци', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-07',
    name: 'Паста за ремонт на стени WallRepair (250 г)',
    description: 'Бързо решение за поправка на малки дефекти по стените без нужда от майстор. Запълва пукнатини, дупки и драскотини. Бързосъхнеща формула, гладък завършек, не се рони и не се лющи. Подходящо за кухня и баня.',
    price: 12.90,
    images: ['/images/products/prod-07/1.jpg','/images/products/prod-07/2.png','/images/products/prod-07/3.jpg','/images/products/prod-07/4.jpg','/images/products/prod-07/5.jpg','/images/products/prod-07/6.jpg','/images/products/prod-07/7.jpg','/images/products/prod-07/8.png','/images/products/prod-07/9.png'],
    category: 'Инструменти', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-08',
    name: 'Абразивни телени кърпи (5 бр.)',
    description: 'Ефективно премахване на мазнини, загорели остатъци и упорита мрасотия без излишно усилие. Не ръждясват и не се деформират, подходящи за многократна употреба. За съдове, пещки, плотове и метални повърхности. 25×20 см.',
    price: 5.90,
    images: ['/images/products/prod-08/1.png','/images/products/prod-08/2.jpg','/images/products/prod-08/3.jpg','/images/products/prod-08/4.jpg','/images/products/prod-08/5.jpg','/images/products/prod-08/6.jpg','/images/products/prod-08/7.jpg','/images/products/prod-08/8.jpg','/images/products/prod-08/9.jpg','/images/products/prod-08/10.jpg','/images/products/prod-08/11.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-09',
    name: 'Антивибрационни крачета SLIPSTOP (4 бр.)',
    description: 'Намаляват вибрациите до 94.7% и премахват досадния шум при работа на перални и сушилни. Предпазват пода от надраскване. Лесен монтаж, универсален размер. Материал: гума + PVC.',
    price: 6.90,
    images: ['/images/products/prod-09/1.png','/images/products/prod-09/2.jpg','/images/products/prod-09/3.jpg','/images/products/prod-09/4.jpg','/images/products/prod-09/5.jpg','/images/products/prod-09/6.jpg','/images/products/prod-09/7.jpg','/images/products/prod-09/8.jpg','/images/products/prod-09/9.jpg','/images/products/prod-09/10.jpg','/images/products/prod-09/11.jpg','/images/products/prod-09/12.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-10',
    name: 'Масажен душ с филтри SHOWERELAX',
    description: 'Няколко режима на водна струя за по-комфортно и релаксиращо изживяване при къпане. Масажиращ и дъждовен ефект. Включени 5 филтра за по-чиста вода. Лесен монтаж за минути, подходящ за всяка стандартна баня.',
    price: 14.90,
    images: ['/images/products/prod-10/1.png','/images/products/prod-10/2.png','/images/products/prod-10/3.jpg','/images/products/prod-10/4.jpg','/images/products/prod-10/5.jpg','/images/products/prod-10/6.png'],
    category: 'Баня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-11',
    name: 'Спрей четка 2 в 1 за прозорци',
    description: 'Почиства и подсушава с един инструмент, без да оставя водни следи. Вграден спрей резервоар, ергономична дръжка против приплъзване. За прозорци, огледала, душ кабини и автомобилни стъкла.',
    price: 9.90,
    images: ['/images/products/prod-11/1.png','/images/products/prod-11/2.jpg','/images/products/prod-11/3.jpg','/images/products/prod-11/4.jpg','/images/products/prod-11/5.jpg','/images/products/prod-11/6.jpg','/images/products/prod-11/7.jpg','/images/products/prod-11/8.jpg','/images/products/prod-11/9.jpg','/images/products/prod-11/10.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-12',
    name: 'Комплект за почистване на хладилник (5 части)',
    description: 'Премахва натрупана мрасотия и бактерии от дренажната система на хладилника. Предотвратява запушвания и течове, намалява неприятните миризми. Гъвкава конструкция за труднодостъпни места, без специални инструменти.',
    price: 12.90,
    images: ['/images/products/prod-12/1.png','/images/products/prod-12/2.jpg','/images/products/prod-12/3.jpg','/images/products/prod-12/4.jpg','/images/products/prod-12/5.jpg','/images/products/prod-12/6.jpg','/images/products/prod-12/7.jpg','/images/products/prod-12/8.jpg','/images/products/prod-12/9.jpg','/images/products/prod-12/10.jpg','/images/products/prod-12/11.jpeg','/images/products/prod-12/12.jpg','/images/products/prod-12/13.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-13',
    name: 'Торбичка за пране на обувки',
    description: 'Дълбоко почистване с микрофибър (шенил), 360° измиване без риск от деформация. Скрит цип за допълнителна защита. Подходяща за спортни и текстилни обувки. Размер: 39.1×19.9 см.',
    price: 9.90,
    images: ['/images/products/prod-13/1.png','/images/products/prod-13/2.jpg','/images/products/prod-13/3.jpg','/images/products/prod-13/4.jpg','/images/products/prod-13/5.jpg','/images/products/prod-13/6.jpg','/images/products/prod-13/7.jpg','/images/products/prod-13/8.jpg','/images/products/prod-13/9.jpg','/images/products/prod-13/10.jpg','/images/products/prod-13/11.jpg','/images/products/prod-13/12.jpg','/images/products/prod-13/13.jpg','/images/products/prod-13/14.jpg','/images/products/prod-13/15.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-14',
    name: 'Комплект за преместване на мебели с лост',
    description: 'Лесно преместване на тежки мебели до 150 кг без усилие и без надраскване на пода. Повдигащ лост + 4 подложки с колела. Без нужда от инструменти. За перални, хладилници, шкафове и пещки.',
    price: 14.90,
    images: ['/images/products/prod-14/1.png','/images/products/prod-14/2.jpg','/images/products/prod-14/3.jpg','/images/products/prod-14/4.jpg','/images/products/prod-14/5.jpg','/images/products/prod-14/6.jpg','/images/products/prod-14/7.jpg','/images/products/prod-14/8.jpg','/images/products/prod-14/9.jpg','/images/products/prod-14/10.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-15',
    name: 'Воден фонтан за домашни любимци 1.5 L',
    description: 'Постоянен поток от свежа и филтрирана вода за котки и кучета. Вграден филтър, 3 режима на воден поток, тиха работа. USB захранване, защита от работа на сухо. Включен резервен филтър. 2.5W.',
    price: 14.90,
    images: ['/images/products/prod-15/1.png','/images/products/prod-15/2.jpg','/images/products/prod-15/3.jpg','/images/products/prod-15/4.jpg','/images/products/prod-15/5.jpg','/images/products/prod-15/6.jpg','/images/products/prod-15/7.jpg','/images/products/prod-15/8.jpg'],
    category: 'Домашни любимци', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-16',
    name: 'LED лампа за четене на книга',
    description: 'Локално осветление директно върху страницата без да се нарушава комфорта на околните. Щадяща светлина за очите, регулируема яркост. Акумулаторна батерия до 35 часа работа. Лек и преносим дизайн.',
    price: 19.99,
    images: ['/images/products/prod-16/1.png','/images/products/prod-16/2.jpg','/images/products/prod-16/3.jpg','/images/products/prod-16/4.jpg','/images/products/prod-16/5.png'],
    category: 'Осветление', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-17',
    name: 'Водоустойчиво хидроизолиращо лепило (300 г)',
    description: 'Запечатва течове, пукнатини и проблемни зони. Устойчиво на дъжд, слънце, студ и влога. Силна адхезия към бетон, метал, дърво и плочки. Лесно нанасяне без специални инструменти. Налично и в 500 г (19.90 лв.).',
    price: 14.90,
    images: ['/images/products/prod-17/1.png','/images/products/prod-17/2.jpg','/images/products/prod-17/3.jpg','/images/products/prod-17/4.jpg','/images/products/prod-17/5.jpg','/images/products/prod-17/6.jpg','/images/products/prod-17/7.jpg'],
    category: 'Инструменти', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-18',
    name: 'Магнитна запечатваща машинка',
    description: 'Запечатва пакети за секунди и поддържа храната свежа по-дълго. Магнитно закрепване към хладилник, вградено острие за отваряне. Дигитален дисплей, 6 температурни нива. Презарежда се (Type C).',
    price: 19.90,
    images: ['/images/products/prod-18/1.png','/images/products/prod-18/2.jpg','/images/products/prod-18/3.jpg','/images/products/prod-18/4.jpg','/images/products/prod-18/5.jpg','/images/products/prod-18/6.jpg','/images/products/prod-18/7.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-19',
    name: 'Преса за коса с вълнообразен ефект',
    description: 'Бързо оформяне на обемни и естествени вълни у дома. Керамично покритие, 4 температурни настройки (160–220°C). Двоен цилиндър за по-бързо оформяне. Защита от прегряване. Цвят лилав, EU 220-240V.',
    price: 24.90,
    images: ['/images/products/prod-19/1.png','/images/products/prod-19/2.png','/images/products/prod-19/3.png','/images/products/prod-19/4.jpg','/images/products/prod-19/5.jpg'],
    category: 'Красота', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-20',
    name: 'Телескопична стойка с колела за мебели',
    description: 'Лесно преместване на тежки мебели и електроуреди до 200 кг без усилие. 12 здрави колела, вградени спирачки за стабилност, телескопичен дизайн. Защитава подовите настилки. За перални, хладилници и шкафове.',
    price: 19.90,
    images: ['/images/products/prod-20/1.png','/images/products/prod-20/2.png','/images/products/prod-20/3.png','/images/products/prod-20/4.png','/images/products/prod-20/5.png','/images/products/prod-20/6.png','/images/products/prod-20/7.jpg','/images/products/prod-20/8.jpg','/images/products/prod-20/9.png'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-21',
    name: 'Ролер за косми FURLOST',
    description: 'Ефективно премахва косми от котки и кучета с едно движение. Без лепящи ленти и консумативи — многократна употреба. Компактен, лесен за пренасяне. За мебели, дрехи, килими и автомобилни седалки. 44×18 см.',
    price: 9.99,
    images: ['/images/products/prod-21/1.png','/images/products/prod-21/2.jpg','/images/products/prod-21/3.jpg','/images/products/prod-21/4.jpg','/images/products/prod-21/5.jpg','/images/products/prod-21/6.jpg','/images/products/prod-21/7.jpg','/images/products/prod-21/8.jpg','/images/products/prod-21/9.jpg'],
    category: 'Домашни любимци', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-22',
    name: 'Безжична мини прахосмукачка VClean 2 в 1',
    description: 'Мощност 9000Pa. Функции: прахосмукачка, издухване и почистване на труднодостъпни места. Акумулаторна батерия 2000mAh, USB зареждане. Комплект 12 части. Тегло 600 г. За дома, автомобила и офиса.',
    price: 19.99,
    images: ['/images/products/prod-22/1.png','/images/products/prod-22/2.png','/images/products/prod-22/3.png','/images/products/prod-22/4.png','/images/products/prod-22/5.png','/images/products/prod-22/6.png','/images/products/prod-22/7.png','/images/products/prod-22/8.png','/images/products/prod-22/9.png','/images/products/prod-22/10.png','/images/products/prod-22/11.png'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-23',
    name: 'Преносим диспенсър за вода за кучета',
    description: 'Превръща стандартна бутилка вода в удобна поилка за кучета по времe на разходки. Сгъваем и компактен дизайн, херметично затваряне против течове. Съвместим с повечето стандартни бутилки. Лесно почистване.',
    price: 9.90,
    images: ['/images/products/prod-23/1.png','/images/products/prod-23/2.jpg','/images/products/prod-23/3.jpg','/images/products/prod-23/4.jpg','/images/products/prod-23/5.jpg','/images/products/prod-23/6.jpg'],
    category: 'Домашни любимци', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-24',
    name: 'Автоматичен сгъваем простор за дрехи (5.1 м)',
    description: 'Метално въже с дължина 5.1 м. Автоматичен прибиращ механизъм — разпъва се при нужда и се прибира след употреба. Здрав и устойчив корпус, лесен монтаж на стена. За апартаменти, бани и тераси.',
    price: 19.90,
    images: ['/images/products/prod-24/1.png','/images/products/prod-24/2.png','/images/products/prod-24/3.jpg','/images/products/prod-24/4.png','/images/products/prod-24/5.jpg','/images/products/prod-24/6.jpg','/images/products/prod-24/7.jpg','/images/products/prod-24/8.jpg','/images/products/prod-24/9.jpg','/images/products/prod-24/10.jpg','/images/products/prod-24/11.jpg','/images/products/prod-24/12.jpg','/images/products/prod-24/13.jpg','/images/products/prod-24/14.png'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-25',
    name: 'Регулируем рафт с закачалка за баня',
    description: 'Комбинира закачалка за кърпи и подвижен рафт за аксесоари. Здрав стоманен корпус, лесен монтаж с включени крепежи. Спестява място в банята. Размер: 57.4×20.5×16.5 см. Цвят: черен.',
    price: 19.99,
    images: ['/images/products/prod-25/1.png','/images/products/prod-25/2.jpg','/images/products/prod-25/3.jpg','/images/products/prod-25/4.jpg','/images/products/prod-25/5.jpg','/images/products/prod-25/6.jpg','/images/products/prod-25/7.jpg','/images/products/prod-25/8.jpg','/images/products/prod-25/9.jpg','/images/products/prod-25/10.jpg'],
    category: 'Баня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-26',
    name: 'Помощна дръжка с вакуумни вендузи',
    description: 'Допълнителна стабилност и безопасност в банята без пробиване или монтаж. Закрепва с вакуумни вендузи за секунди. Лесно преместване и повторна употреба. За плочки, стъкло и твърда пластмаса.',
    price: 12.90,
    images: ['/images/products/prod-26/1.png','/images/products/prod-26/2.jpg','/images/products/prod-26/3.jpg','/images/products/prod-26/4.jpg','/images/products/prod-26/5.jpg','/images/products/prod-26/6.jpg','/images/products/prod-26/7.jpg','/images/products/prod-26/8.jpg','/images/products/prod-26/9.jpg','/images/products/prod-26/10.jpg','/images/products/prod-26/11.jpg'],
    category: 'Баня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-27',
    name: 'Безжични LED светлини за автомобил / дрон (4 бр.)',
    description: '8 цвята светлина, 10 режима на работа. Дистанционно управление до 7 м, USB презареждане, водоустойчивост IP65. Функция памет на последния режим. За автомобили, мотори, велосипеди и дронове.',
    price: 14.90,
    images: ['/images/products/prod-27/1.png','/images/products/prod-27/2.jpg','/images/products/prod-27/3.jpg','/images/products/prod-27/4.jpg','/images/products/prod-27/5.jpg','/images/products/prod-27/6.jpg','/images/products/prod-27/7.jpg','/images/products/prod-27/8.jpg','/images/products/prod-27/9.jpg','/images/products/prod-27/10.jpg','/images/products/prod-27/11.jpg','/images/products/prod-27/12.jpg','/images/products/prod-27/13.jpg'],
    category: 'Автомобили', inStock: true, minOrder: 1, unit: 'компл.',
  },
  {
    id: 'prod-28',
    name: 'Соларна LED лампа за къмпинг',
    description: 'Слънчево и USB-C зареждане, до 10 часа работа. 3 режима на светлина (силен, среден, слаб). Вградена кука за окачване, лека и компактна. За къмпинг, риболов, туризъм, градина и аварийни ситуации.',
    price: 4.90,
    images: ['/images/products/prod-28/1.png','/images/products/prod-28/2.jpg','/images/products/prod-28/3.jpg','/images/products/prod-28/4.jpg','/images/products/prod-28/5.jpg','/images/products/prod-28/6.jpg','/images/products/prod-28/7.jpg','/images/products/prod-28/8.jpg','/images/products/prod-28/9.jpg','/images/products/prod-28/10.jpg'],
    category: 'Осветление', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-29',
    name: '3D увеличителен екран за смартфон',
    description: 'Увеличава изображението до 5 пъти и намалява напрежението в очите. Сгъваем и компактен дизайн, работи с всички смартфони без настройки. HD акрилна леща. За филми, TikTok, YouTube и видео разговори.',
    price: 9.99,
    images: ['/images/products/prod-29/1.png','/images/products/prod-29/2.jpg','/images/products/prod-29/3.jpeg','/images/products/prod-29/4.jpg','/images/products/prod-29/5.jpg','/images/products/prod-29/6.jpg','/images/products/prod-29/7.jpg','/images/products/prod-29/8.jpg','/images/products/prod-29/9.jpg','/images/products/prod-29/10.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-30',
    name: 'Удължител за кухненски кран (аератор)',
    description: '360° въртящ се накрайник против пръски. Икономия на вода без загуба на налягане. Бърз монтаж без инструменти. Подходящ за кухня и баня. Лесно поставяне и сваляне. Цвят: сребрист / черен.',
    price: 9.99,
    images: ['/images/products/prod-30/1.png','/images/products/prod-30/2.jpg','/images/products/prod-30/3.jpg','/images/products/prod-30/4.jpg','/images/products/prod-30/5.jpg','/images/products/prod-30/6.jpg','/images/products/prod-30/7.jpg','/images/products/prod-30/8.jpg','/images/products/prod-30/9.jpg'],
    category: 'Дом & Кухня', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-31',
    name: 'Дигитален нивелир с LCD дисплей',
    description: 'Точност до 0.01°, измерване на 360°. Магнитна основа за стабилно закрепване. Моментални измервания в реално времe. Устойчив на удари и влога. За монтаж на мебели, гипсокартон, строителни конструкции.',
    price: 24.90,
    images: ['/images/products/prod-31/1.png','/images/products/prod-31/2.jpg','/images/products/prod-31/3.jpg','/images/products/prod-31/4.jpg','/images/products/prod-31/5.jpg','/images/products/prod-31/6.jpg','/images/products/prod-31/7.jpg','/images/products/prod-31/8.jpg','/images/products/prod-31/9.jpg','/images/products/prod-31/10.jpg'],
    category: 'Инструменти', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-32',
    name: 'Спрей четка за коса 2 в 1',
    description: 'Разресва и овлажнява едновременно. Вграден пулверизатор за фина мъгла, намалява скъбването и накъсването. Ергономична дръжка, вграден резервоар за вода или балсам. По-гладка и освежена коса за секунди.',
    price: 14.90,
    images: ['/images/products/prod-32/1.png','/images/products/prod-32/2.jpg','/images/products/prod-32/3.jpg','/images/products/prod-32/4.jpg','/images/products/prod-32/5.jpg','/images/products/prod-32/6.jpg','/images/products/prod-32/7.jpg','/images/products/prod-32/8.jpg','/images/products/prod-32/9.jpg','/images/products/prod-32/10.jpg','/images/products/prod-32/11.jpg','/images/products/prod-32/12.jpg','/images/products/prod-32/13.png'],
    category: 'Красота', inStock: true, minOrder: 1, unit: 'бр.',
  },
  {
    id: 'prod-33',
    name: 'Четки за винтоверт (3 бр.)',
    description: 'Захващат упорита мрасотия за минути. Съвместими с винтоверт и бормашина. 3 различни размера, достигат труднодостъпни места. Не драскат повърхностите при правилна употреба. За бани, джанти, фуги и мебели.',
    price: 12.90,
    images: ['/images/products/prod-33/1.png','/images/products/prod-33/2.png','/images/products/prod-33/3.png','/images/products/prod-33/4.png','/images/products/prod-33/5.jpg','/images/products/prod-33/6.jpg','/images/products/prod-33/7.jpg','/images/products/prod-33/8.jpg','/images/products/prod-33/9.png','/images/products/prod-33/10.png','/images/products/prod-33/11.jpg'],
    category: 'Инструменти', inStock: true, minOrder: 1, unit: 'компл.',
  },
]

export function getProduct(id: string): Product | undefined {
  return products.find(p => p.id === id)
}

export function getProducts(category?: string): Product[] {
  if (!category || category === 'Всички') return products
  return products.filter(p => p.category === category)
}
